## Sampling & Storing Datasets

In [1]:
# creating pairs of the datasets
import os
import numpy as np 

numpy_dir = '/Volumes/JOE_LOUIS/peaks.bedgraph/workspace/numpy_datasets/'

ml_pairs = []

for file_X in os.listdir(numpy_dir):
    if file_X.startswith('X'):
        file_name_X = file_X.split('.')[2]
        for file_y in os.listdir(numpy_dir):
            if file_y.startswith('y'):
                file_name_y = file_y.split('.')[2]
                if file_name_X == file_name_y:
                    ml_pairs.append([file_X,file_y])

print(ml_pairs)


[['X.0.Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2.npy', 'y.0.Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2.npy'], ['X.1.Adelman_Dmel_S2_H3K4me1_ChIP-seq_rep1and2.npy', 'y.1.Adelman_Dmel_S2_H3K4me1_ChIP-seq_rep1and2.npy'], ['X.2.Adelman_Dmel_S2_H3K4me3_ChIP-seq_rep1and2.npy', 'y.2.Adelman_Dmel_S2_H3K4me3_ChIP-seq_rep1and2.npy'], ['X.3.Adelman_Dmel_S2_NELF-B_ChIP-seq_rep1and2.npy', 'y.3.Adelman_Dmel_S2_NELF-B_ChIP-seq_rep1and2.npy'], ['X.4.Adelman_Dmel_S2_RNAPolII_ChIP-seq_control_rep1and2_normalized.npy', 'y.4.Adelman_Dmel_S2_RNAPolII_ChIP-seq_control_rep1and2_normalized.npy'], ['X.5.GSE101365_idr-macs2-mock_ago2_mueller.npy', 'y.5.GSE101365_idr-macs2-mock_ago2_mueller.npy'], ['X.6.GSE101554_S2_Ez_ChIP_peaks.npy', 'y.6.GSE101554_S2_Ez_ChIP_peaks.npy'], ['X.7.GSE101554_S2_GAF_ChIP_peaks.npy', 'y.7.GSE101554_S2_GAF_ChIP_peaks.npy'], ['X.8.GSE101554_S2_HA_ChIP.npy', 'y.8.GSE101554_S2_HA_ChIP.npy'], ['X.9.GSE101554_S2_M1BP_ChIP_peaks.npy', 'y.9.GSE101554_S2_M1BP_ChIP_peaks.npy'], ['X.10.GSE10155

In [2]:
# sampling from ml pairs
numpy_dir = '/Volumes/JOE_LOUIS/peaks.bedgraph/workspace/numpy_datasets/'

# loading datasets
X = np.load(numpy_dir + ml_pairs[0][0])
y = np.load(numpy_dir + ml_pairs[0][1])
print(f'Sampling {ml_pairs[0][0].split(".")[2]}...')

# sample
sampled_indices = np.random.choice(X.shape[0],size=200,replace=False)
X_boot = X[sampled_indices,:]
y_boot = y[sampled_indices]

for pair in ml_pairs[1:]:

    # loading datasets
    X = np.load(numpy_dir + pair[0])
    y = np.load(numpy_dir + pair[1])
    print(f'Sampling {pair[0].split(".")[2]}...')

    if X.shape[0] >= 200:
        # sample
        sampled_indices = np.random.choice(X.shape[0],size=200,replace=False)
        sampled_seqs = X[sampled_indices,:]
        sampled_labs = y[sampled_indices]

        # concat to final feature matrix
        X_boot = np.concatenate([X_boot,sampled_seqs],axis=0)
        y_boot = np.concatenate([y_boot,sampled_labs],axis=0)
    
    else:
        # concat to final feature matrix with all seqs
        X_boot = np.concatenate([X_boot,sampled_seqs],axis=0)
        y_boot = np.concatenate([y_boot,sampled_labs],axis=0)


print(X_boot.shape)
print(y_boot.shape)

Sampling Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2...
Sampling Adelman_Dmel_S2_H3K4me1_ChIP-seq_rep1and2...
Sampling Adelman_Dmel_S2_H3K4me3_ChIP-seq_rep1and2...
Sampling Adelman_Dmel_S2_NELF-B_ChIP-seq_rep1and2...
Sampling Adelman_Dmel_S2_RNAPolII_ChIP-seq_control_rep1and2_normalized...
Sampling GSE101365_idr-macs2-mock_ago2_mueller...
Sampling GSE101554_S2_Ez_ChIP_peaks...
Sampling GSE101554_S2_GAF_ChIP_peaks...
Sampling GSE101554_S2_HA_ChIP...
Sampling GSE101554_S2_M1BP_ChIP_peaks...
Sampling GSE101554_S2_Rpb3_ChIP_peaks...
Sampling GSE101554_S2_dRing_ChIP_peaks...
Sampling GSE37864_mle...
Sampling GSE37864_mof...
Sampling GSE37864_msl1...
Sampling GSE37864_msl2...
Sampling GSE37864_msl3...
Sampling GSE85191_Adelman_Dmel_S2_Cohesin_ChIP-seq_rep1and2...
Sampling GSE99004_macs_1WTgA...
Sampling GSE99004_macs_1dH1gA...
Sampling GSE99004_macs_2WTgA...
Sampling GSE99004_macs_2dH1gA...
Sampling GSM1015406_CtSuHw_peaks...
Sampling GSM1015408_CtMod_peaks...
Sampling GSM1015410_Ct-CTCF_peaks

In [3]:
# saving the sampled dataset
# np.save('X.boot.200.npy',X_boot)
# np.save('y.boot.200.npy',y_boot)

## CNN: preprocessing & constructing model

In [1]:
# loading sample datasets
import numpy as np
X_boot = np.load('X.boot.200.npy')
y_boot = np.load('y.boot.200.npy')

In [5]:
X_boot = X_boot.tolist()
X_boot = [lst[1:-1] for lst in X_boot]

# final = []
# temp = []
# for lst in X_boot:
#     seq = ''.join(lst[1:-1])
#     temp.extend([lst[0],seq])
#     final.append(temp)
#     temp = []

In [12]:
final[0:2]

[['Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2',
  'ACTCTTTTCTCACAAAAAAATATTTTTTTCTCTCTTTTTTTTTTGTGCGCTCTTTTTTTCTCGCGAGATATTTTATATATGTGGGGGGGAGAAAAGAGAGATATTTTTTTTTTGTGGGGAGAAAAGAGTGTGTGAGAAAATATTTTTTTGTGAGAGAGGGGAGAGAGAGACACTCTCTCTCTCTCGCGGGGAGAAAATATTTTATACACACAGAGAGAGAGCGCGCGAGAGAGAGATATTTTGTGCGCGCGTGTGTGGGGTGTGTGCGCCCCACATATATACACACAAAAAAAGAGTGTTTTATAAAACACTCTGTGGGGGGGAGATATCTCGCGGGGTGTATACACTCTTTTTTTTTTTTTGTGTGTGTGTGTGTGTGTATAAAAGAGAGAGAGAGATATGTGTGTGTGCGCGCGTGTTTTTTTCTCTCTTTTGTGAGATATGTGAGACACACAGAGAGATATGTGAGATATTTTTTTTTTTTTCTCGCGGGGTGTTTTGTGTGTATATATCTCGCGTGTTTTTTTTTTATATATTTTATAGAGGGGAGATATTTTATAGAGTGTATAAAATATTTTCTCGCGTGTTTTGTGTGTATAGAGTGTTTTGTGTGTTTTCTCTCTGTGGGGTGTATATATCTCCCCACATATTTTCTCACATATGTGAGATATNTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

In [ ]:
import numpy as np

# Define a function to one-hot encode a single DNA sequence
def one_hot_encode(sequence, seq_id, bases):
    encoding = np.zeros((len(sequence) + 1, len(bases)))
    # Set the first row of the encoding to the one-hot encoding of the sequence ID
    encoding[0, :] = one_hot_encode_sequence_id(seq_id, bases)
    for i, base in enumerate(sequence):
        if base in bases:
            encoding[i + 1, bases.index(base)] = 1
    return encoding

# Define a function to one-hot encode a sequence ID
def one_hot_encode_sequence_id(seq_id, bases):
    encoding = np.zeros((len(bases)))
    for i, base in enumerate(seq_id):
        if base in bases:
            encoding[bases.index(base)] = 1
    return encoding

# Define a function to one-hot encode a nested list of DNA sequences
def nested_one_hot_encode(nested_sequences, bases):
    encoded_sequences = []
    for i, sequence in enumerate(nested_sequences):
        # Extract the sequence ID and actual sequence from the input
        seq_id, seq = sequence[0], sequence[1]
        # One-hot encode the sequence and add the sequence ID as the first row
        encoded_sequence = one_hot_encode(seq, seq_id, bases)
        encoded_sequences.append(encoded_sequence)
    return encoded_sequences

# Example usage
# sequences = [['seq1', 'ATCG'], ['seq2', 'CGTA'], ['seq3', 'NTCG']]
bases = 'ATCGN'
encoded_sequences = nested_one_hot_encode(final, bases)
print(encoded_sequences)

In [34]:
np.array(encoded_sequences)[0]

array([[1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [13]:
encoded_sequences = np.array(encoded_sequences)
# np.save("X.boot.200.CNN.npy",encoded_sequences)
# np.save("y.boot.200.CNN.npy",y_boot)

In [1]:
import numpy as np
X_boot = np.load('./X.boot.200.CNN.npy')
y_boot = np.load('./y.boot.200.CNN.npy')

In [2]:
import pandas as pd
import numpy as np
y_boot = pd.Series(y_boot)
y_boot = y_boot.replace(False,0)
y_boot = y_boot.replace(True,1)
y_boot = np.array(y_boot)

In [3]:
print(X_boot.shape)
print(y_boot.shape)

(13600, 2994, 5)
(13600,)


In [12]:
from sklearn.model_selection import train_test_split

# splitting dataset
X_train,X_other,y_train,y_other = train_test_split(X_boot,y_boot,train_size=0.6,random_state=3,stratify=y_boot)
X_val,X_test,y_val,y_test = train_test_split(X_other,y_other,train_size=0.5,random_state=3,stratify=y_other)

print(np.shape(X_train),np.shape(X_test),np.shape(y_train),np.shape(y_test))
print(X_train[3])
print(y_train[3])

(8160, 2994, 5) (2720, 2994, 5) (8160,) (2720,)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
1


In [13]:
# Build your CNN model with the appropriate input shape and other hyperparameters
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv1D(
        filters=10, kernel_size=20, activation='leaky_relu', 
        strides = 1, padding = 'SAME'),
    tf.keras.layers.MaxPooling1D(
        pool_size=2),
    tf.keras.layers.Conv1D(
        filters=50, kernel_size=20, activation='leaky_relu',
       strides = 1, padding = 'SAME'),
    tf.keras.layers.MaxPooling1D(
        pool_size=2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=128, activation='leaky_relu',activity_regularizer=tf.keras.regularizers.L2(0.1)),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Dense(units=12, activation='leaky_relu',activity_regularizer=tf.keras.regularizers.L2(0.1)),
    tf.keras.layers.Dropout(rate=0.5),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# parameters
opt = tf.keras.optimizers.Adam(learning_rate=0.0005)
loss = tf.keras.losses.BinaryCrossentropy(from_logits=False)

# Train your model with the one-hot encoded sequences
model.compile(
    optimizer=opt, 
    loss=loss, 
    metrics=['accuracy']
    )
model.fit(
    X_train, y_train, 
    epochs=10, 
    batch_size=100,
    validation_data=(X_val,y_val)
    )

Epoch 1/10
82/82 [==============================] - 28s 324ms/step - loss: 0.7119 - accuracy: 0.7532 - val_loss: 0.6226 - val_accuracy: 0.7868
Epoch 2/10
82/82 [==============================] - 27s 334ms/step - loss: 0.6110 - accuracy: 0.7900 - val_loss: 0.6080 - val_accuracy: 0.7893
Epoch 3/10
82/82 [==============================] - 29s 349ms/step - loss: 0.5785 - accuracy: 0.8029 - val_loss: 0.5876 - val_accuracy: 0.7971
Epoch 4/10
82/82 [==============================] - 30s 366ms/step - loss: 0.5376 - accuracy: 0.8282 - val_loss: 0.5781 - val_accuracy: 0.8022
Epoch 5/10
82/82 [==============================] - 32s 385ms/step - loss: 0.4980 - accuracy: 0.8575 - val_loss: 0.5833 - val_accuracy: 0.7904
Epoch 6/10
82/82 [==============================] - 41s 504ms/step - loss: 0.4507 - accuracy: 0.8969 - val_loss: 0.5760 - val_accuracy: 0.8015
Epoch 7/10
82/82 [==============================] - 31s 375ms/step - loss: 0.4071 - accuracy: 0.9228 - val_loss: 0.5775 - val_accuracy: 0.7875

In [14]:
model.evaluate(
    X_test,y_test,batch_size=100
)

28/28 [==============================] - 2s 85ms/step - loss: 0.5691 - accuracy: 0.7941


[0.5690501928329468, 0.7941176295280457]

In [15]:
model.save(
    'cnn.R3.mod'
)

INFO:tensorflow:Assets written to: cnn.R3.mod/assets


INFO:tensorflow:Assets written to: cnn.R3.mod/assets


In [8]:
import pandas as pd 
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print(f"Baseline Acc: {baseline}")

Baseline Acc: 0.787


In [ ]:
import shap

@jit(nopython=True)
def my_numba_function():
    # function body

    shap.initjs()
    # Need input shape for Keras model 
    # model = tf.keras.models.load_model('encoder') # if we have a saved model file
    # model = encoder # if model is just stored as an object in the notebook

    data = X_boot[np.random.choice(X_boot.shape[0],  size = 100, replace = False)] #set size to n. of points to explain
    explainer = shap.DeepExplainer(model, data) # subset of training data
    shap_values = explainer.shap_values(data) # may need to put test data here
    shap.summary_plot(shap_values, data) # adjust

my_numba_function()

## Transformer (K = 8): Preprocessing & constructing transformer

In [36]:
# loading sample datasets
import numpy as np
X_boot = np.load('X.boot.200.npy')
y_boot = np.load('y.boot.200.npy')

In [37]:
X_boot = X_boot.tolist()
X_boot = [lst[:] for lst in X_boot]
final = []
temp = []
for lst in X_boot:
    seq = ''.join(lst[1:-1])
    temp.extend([lst[0],seq])
    final.append(temp)
    temp = []

In [39]:
kmer_length = 8

output_list = []
for seq in final:
    seq_id = seq[0]
    seq_string = seq[1]
    kmers = [seq_string[i:i+kmer_length] for i in range(len(seq_string)-kmer_length+1) if len(seq_string[i:i+kmer_length]) == kmer_length]
    kmers.append('<END>')
    output_list.append([seq_id] + kmers)

In [40]:
np.array(output_list).shape

(13600, 2989)

In [41]:
X_boot = np.array(output_list)
# np.save('X.boot.200.k8.npy',X_boot)
# np.save('y.boot.200.k8.npy',y_boot)

In [ ]:
X_boot = np.load('X.boot.200.k8.npy')
y_boot = np.load('y.boot.200.k8.npy')

In [42]:
print(X_boot.shape)
X_boot = X_boot[:,:1000]
print(X_boot.shape)

(13600, 2989)
(13600, 1000)


In [43]:
import pandas as pd
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print("Baseline Acc:",baseline)

Baseline Acc: 0.787


In [44]:
# obtaining keys to use in dictionary =
import numpy as np

def get_unique_items(nested_list):
    unique_items = set()
    for item in nested_list:
        if isinstance(item, list):
            unique_items.update(get_unique_items(item))
        else:
            unique_items.add(item)
    return unique_items

all_keys = get_unique_items(X_boot.tolist())
print(all_keys)

{'AAGAGNGN', 'TTTATANA', 'AAAGAGNG', 'GACACACA', 'AAAAGAGN', 'GTGNGNNN', 'ATATTTTN', 'GSM1535966_CapH2_NT_Rep1', 'TTTGTGAG', 'CTCCCCTC', 'AGGGGTGT', 'TTTCTCAC', 'CCCCCCCG', 'AACACTCT', 'CANANNNN', 'AGATATCT', 'TATATTTT', 'NGNGAGAC', 'GGGGTGTN', 'CNCTCTCT', 'CCCCCNCN', 'GTGTTTTC', 'TGTGGGGA', 'GAGAGACA', 'CTCGCGAG', 'ATTTTCTC', 'TTTTCTCA', 'AAAAAGAG', 'AAACACAC', 'CACAAAAC', 'GTGTNTNN', 'GCGCGCTC', 'ATATATAC', 'TACACACA', 'CGAGACAC', 'GATATCTC', 'GGTGTATA', 'NATATGTG', 'ANAAAAGA', 'GTGTCTCC', 'ACATATCT', 'AGGGGAGA', 'GAGATATN', 'AAAAAAAN', 'NGAGAGAG', 'TGTGTTTT', 'GGGGCGCN', 'AAATATNT', 'TCTCTCTC', 'TCTCACAG', 'GCGCACAN', 'NANAGAGC', 'CTTTTCTC', 'TCTTTTAT', 'TCTGTGCG', 'AAAATATA', 'GGAGAAAA', 'GGGAGAAA', 'ACACTCTA', 'GSM2133764_Kc_H3K27me3', 'CGAGAGAG', 'CACACGCG', 'ATAGAGCG', 'GSE101554_S2_Ez_ChIP_peaks', 'TGGGGCGC', 'GSM1535971_CBP_NT_Rep2', 'GNGCGCGC', 'ACTCTNTN', 'GAGCGCGC', 'CACTCTTT', 'GTGTGTGA', 'CACACAAA', 'AACACACA', 'NTTTTTTT', 'CTATATAT', 'CGCGGGGC', 'GAGAGAGT', 'NANACACG', '

In [45]:
# constructing dictionary
dna_dict = {}
counter = 0 
for i in all_keys:
    dna_dict[i] = counter
    counter+=1

print("Number of Items in Dictionary:",len(dna_dict))

Number of Items in Dictionary: 1268


In [46]:
# replacing keys with values in the dataset
print("Original Sequence:",X_boot.tolist()[0][:5])

def replace_values(nested_list, dictionary):
    """
    Given a nested list, replaces every item with the corresponding value in a dictionary.
    """
    if isinstance(nested_list, list):
        return [replace_values(item, dictionary) for item in nested_list]
    elif nested_list in dictionary:
        return dictionary[nested_list]
    else:
        return nested_list

seqs_out = replace_values(X_boot.tolist(),dna_dict)
print("Updated Sequence:",seqs_out[0][:5])

Original Sequence: ['Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2', 'ACTCTTTT', 'CTCTTTTC', 'TCTTTTCT', 'CTTTTCTC']
Updated Sequence: [195, 1158, 1122, 467, 52]


In [47]:
X_boot = np.array(seqs_out)
y_boot = np.array(y_boot)

In [48]:
np.save('X.boot.200.k8.processed.npy',X_boot)
np.save('y.boot.200.k8.processed.npy',y_boot)

In [31]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
X_train,X_other,y_train,y_other = train_test_split(X_boot,y_boot,train_size=0.8,stratify=y_boot,random_state=22)
X_val,X_test,y_val,y_test = train_test_split(X_other,y_other,train_size=0.5,stratify=y_other,random_state=22)

In [ ]:
import numpy as np
import tensorflow as tf
from transformer import TransformerEncoder
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam

# Testing model
encoder = TransformerEncoder(
    vocab_size=1268,
    emb_sz=64,
    num_of_blocks=2,
    num_of_atten_heads=4,
    window_size=1000)

encoder.compile(
    optimizer = Adam(learning_rate=0.001),
    loss = BinaryCrossentropy(from_logits=False),
    metrics=['acc']
)
encoder.fit(
    X_train,y_train,
    epochs=5,batch_size=100,
    validation_data=(X_val,y_val)
)

In [34]:
encoder.evaluate(
    X_test,y_test,batch_size = 50
)

28/28 [==============================] - 11s 393ms/step - loss: 1.0230 - acc: 0.8250


[1.0230218172073364, 0.824999988079071]

In [32]:
import pandas as pd
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print("Baseline Acc:",baseline)

Baseline Acc: 0.787


## Transformer (K = 5): Preprocessing & constructing transformer

In [1]:
# loading sample datasets
import numpy as np
X_boot = np.load('X.boot.200.npy')
y_boot = np.load('y.boot.200.npy')

In [2]:
print(X_boot.shape)
print(y_boot.shape)

(13600, 1000)
(13600,)


In [3]:
X_boot = X_boot.tolist()
X_boot = [lst[:] for lst in X_boot]
final = []
temp = []
for lst in X_boot:
    seq = ''.join(lst[1:-1])
    temp.extend([lst[0],seq])
    final.append(temp)
    temp = []

In [4]:
kmer_length = 5

output_list = []
for seq in final:
    seq_id = seq[0]
    seq_string = seq[1]
    kmers = [seq_string[i:i+kmer_length] for i in range(len(seq_string)-kmer_length+1) if len(seq_string[i:i+kmer_length]) == kmer_length]
    kmers.append('<END>')
    output_list.append([seq_id] + kmers)

In [5]:
np.array(output_list).shape

(13600, 2992)

In [6]:
X_boot = np.array(output_list)
# np.save('X.boot.200.k5.npy',X_boot)
# np.save('y.boot.200.k5.npy',y_boot)

In [7]:
import numpy as np
X_boot = np.load('X.boot.200.k5.npy')
y_boot = np.load('y.boot.200.k5.npy')

In [7]:
print(X_boot.shape)
X_boot = X_boot[:,:1000]
print(X_boot.shape)

(13600, 2992)
(13600, 1000)


In [8]:
import pandas as pd
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print("Baseline Acc:",baseline)

Baseline Acc: 0.787


In [9]:
# obtaining keys to use in dictionary =
import numpy as np

def get_unique_items(nested_list):
    unique_items = set()
    for item in nested_list:
        if isinstance(item, list):
            unique_items.update(get_unique_items(item))
        else:
            unique_items.add(item)
    return unique_items

all_keys = get_unique_items(X_boot.tolist())
print(all_keys)

{'GTATA', 'GGGGC', 'GAGAA', 'CGCGT', 'CTCAC', 'GAGGG', 'AACAC', 'GSM948714_e16-18hr_FAIRE_peaks', 'CAAAA', 'GTTTT', 'GSM2133768_Kc_Pita', 'ATATT', 'GSM1015408_CtMod_peaks', 'GSM1535970_CBP_NT_Rep1', 'CCCAC', 'CGGGG', 'NANAT', 'TCTGT', 'NANAC', 'CTCTC', 'CANAN', 'TGAGA', 'GSE101554_S2_Ez_ChIP_peaks', 'TCTAT', 'GSM2860390_GFPRNAi_GAFIP_R1_peaks', 'AAAAA', 'GSM948712_e2-4hr_FAIRE_peaks', 'NTGTG', 'TNTTT', 'AAATA', 'NGNGA', 'GSM2133767_Kc_Ibf2', 'GSM2860394_GFPRNAi_GAFIP_R2_peaks', 'CCCCG', 'TTCTC', 'GGGCG', 'GSM1535971_CBP_NT_Rep2', 'CCTCT', 'TCTTT', 'AAAAC', 'NGCGC', 'GSM2133769_Kc_ZIPIC', 'GSE37864_msl3', 'AGAGA', 'TCTCN', 'TCCCC', 'NNANA', 'TATNT', 'GGGGN', 'ATAAA', 'NGTGT', 'NTNTT', 'AAAAT', 'NNNNN', 'GSE101554_S2_Rpb3_ChIP_peaks', 'GNGNN', 'GNGCG', 'CNNNN', 'CAGAG', 'GGGAG', 'ATNTN', 'GSM1535980_CP190_NT_Rep2', 'CNCCC', 'GSM1535983_CTCF_NT_Rep2', 'CCCGC', 'CTCNC', 'GCGCC', 'TNTNN', 'NNGNG', 'NAGAG', 'GSE37864_mof', 'GSM2133770_Kc_Nup98', 'TTGTG', 'TCTCC', 'CACGC', 'GSE101554_S2_dRing

In [10]:
# constructing dictionary
dna_dict = {}
counter = 0 
for i in all_keys:
    dna_dict[i] = counter
    counter+=1

print("Number of Items in Dictionary:",len(dna_dict))

Number of Items in Dictionary: 344


In [11]:
# replacing keys with values in the dataset
print("Original Sequence:",X_boot.tolist()[0][:5])

def replace_values(nested_list, dictionary):
    """
    Given a nested list, replaces every item with the corresponding value in a dictionary.
    """
    if isinstance(nested_list, list):
        return [replace_values(item, dictionary) for item in nested_list]
    elif nested_list in dictionary:
        return dictionary[nested_list]
    else:
        return nested_list

seqs_out = replace_values(X_boot.tolist(),dna_dict)
print("Updated Sequence:",seqs_out[0][:5])

Original Sequence: ['Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2', 'ACTCT', 'CTCTT', 'TCTTT', 'CTTTT']
Updated Sequence: [267, 168, 108, 38, 190]


In [12]:
X_boot = np.array(seqs_out)
y_boot = np.array(y_boot)

In [65]:
np.save('X.boot.200.k5.processed.npy',X_boot)
np.save('y.boot.200.k5.processed.npy',y_boot)

In [13]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
X_train,X_other,y_train,y_other = train_test_split(X_boot,y_boot,train_size=0.8,stratify=y_boot,random_state=1)
X_val,X_test,y_val,y_test = train_test_split(X_other,y_other,train_size=0.5,stratify=y_other,random_state=1)

2023-05-07 19:58:14.121958: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
import numpy as np
import tensorflow as tf
from transformer import TransformerEncoder
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam

# Testing model
encoder = TransformerEncoder(
    vocab_size=344,
    emb_sz=64,
    num_of_blocks=1,
    num_of_atten_heads=4,
    window_size=1000)

encoder.compile(
    optimizer = Adam(learning_rate=0.001),
    loss = BinaryCrossentropy(from_logits=False),
    metrics=['acc']
)
encoder.fit(
    X_train,y_train,
    epochs=5,batch_size=100,
    validation_data=(X_val,y_val)
)

2023-05-07 19:58:37.670580: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/5
109/109 [==============================] - 473s 4s/step - loss: 2.8001 - acc: 0.6923 - val_loss: 5.3120 - val_acc: 0.2125
Epoch 2/5
109/109 [==============================] - 501s 5s/step - loss: 0.9927 - acc: 0.7377 - val_loss: 0.5952 - val_acc: 0.8191
Epoch 3/5
109/109 [==============================] - 534s 5s/step - loss: 0.5167 - acc: 0.7995 - val_loss: 0.8042 - val_acc: 0.8191
Epoch 4/5
109/109 [==============================] - 515s 5s/step - loss: 0.4529 - acc: 0.8271 - val_loss: 0.5407 - val_acc: 0.7838
Epoch 5/5
109/109 [==============================] - 520s 5s/step - loss: 0.3823 - acc: 0.8459 - val_loss: 0.7700 - val_acc: 0.8250


In [18]:
encoder.evaluate(
    X_test,y_test,batch_size=100
)

14/14 [==============================] - 15s 1s/step - loss: 0.8366 - acc: 0.8154


[0.8366251587867737, 0.8154411911964417]

In [ ]:
encoder.save(
    'encoder.k5.R3.mod'
)

In [18]:
import pandas as pd
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print("Baseline Acc:",baseline)

Baseline Acc: 0.787


## Transformer (K = 3): Preprocessing & constructing transformer

In [66]:
# loading sample datasets
import numpy as np
X_boot = np.load('X.boot.200.npy')
y_boot = np.load('y.boot.200.npy')

In [67]:
print(X_boot[0][0:5])
print(y_boot[0:5])

['Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2' 'ACT' 'CTT' 'TTC' 'TCA']
[ True False  True  True False]


In [68]:
import pandas as pd
baseline = pd.DataFrame(y_boot).value_counts()[0] / pd.DataFrame(y_boot).value_counts().sum()
baseline = "{:.3f}".format(baseline)
print("Baseline Acc:",baseline)

Baseline Acc: 0.787


In [69]:
# obtaining keys to use in dictionary =
import numpy as np

def get_unique_items(nested_list):
    unique_items = set()
    for item in nested_list:
        if isinstance(item, list):
            unique_items.update(get_unique_items(item))
        else:
            unique_items.add(item)
    return unique_items

all_keys = get_unique_items(X_boot.tolist())
print(all_keys)

{'AAG', 'TGT', 'GSM1015406_CtSuHw_peaks', 'TCT', 'CTN', 'GSM1535970_CBP_NT_Rep1', 'GSM948712_e2-4hr_FAIRE_peaks', 'GGN', 'CCG', 'GSM1535976_Chromator_NT_Rep2', 'GTT', 'GSE101554_S2_HA_ChIP', 'GSM1535966_CapH2_NT_Rep1', 'GSE101554_S2_Rpb3_ChIP_peaks', 'GSE101554_S2_dRing_ChIP_peaks', 'NGA', 'GSM2133769_Kc_ZIPIC', 'Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2', 'AGA', 'CAC', 'NTT', 'AGG', 'GSM1535963_BEAF_NT_Rep2', 'TTA', 'GSE37864_msl1', 'AGN', 'ATA', 'GAC', 'GSM2487550_H3_3', 'GSM1535987_Fs1h-L_NT_Rep1', 'CTG', 'GTC', 'GSM2133770_Kc_Nup98', 'CTC', 'GCA', 'CGC', 'NCT', 'GSM2443787_Ash1-in-WT', 'AGT', '<END>', 'TTN', 'ACA', 'CTA', 'CAA', 'GSM2202474_Gcn5_GFP_RNAi_macs14_peaks', 'CGA', 'NCA', 'GSM892323_L3mbt', 'TCC', 'GCN', 'GSM2860389_GFPRNAi_ClampIP_R1_peaks', 'NNN', 'GTG', 'GAA', 'TGN', 'TTC', 'ACT', 'GAG', 'CCA', 'GGC', 'Adelman_Dmel_S2_RNAPolII_ChIP-seq_control_rep1and2_normalized', 'GSM2860398_GFPRNAi_GAFIP_R3_peaks', 'GSM2133764_Kc_H3K27me3', 'GAT', 'GCG', 'GSE101554_S2_Ez_ChIP_peaks

In [70]:
# constructing dictionary
dna_dict = {}
counter = 0 
for i in all_keys:
    dna_dict[i] = counter
    counter+=1

print("Number of Items in Dictionary:",len(dna_dict))

Number of Items in Dictionary: 170


In [71]:
# replacing keys with values in the dataset
print("Original Sequence:",X_boot.tolist()[0][:5])

def replace_values(nested_list, dictionary):
    """
    Given a nested list, replaces every item with the corresponding value in a dictionary.
    """
    if isinstance(nested_list, list):
        return [replace_values(item, dictionary) for item in nested_list]
    elif nested_list in dictionary:
        return dictionary[nested_list]
    else:
        return nested_list

seqs_out = replace_values(X_boot.tolist(),dna_dict)
print("Updated Sequence:",seqs_out[0][:5])

Original Sequence: ['Adelman_Dmel_S2_H3K27ac_ChIP-seq_rep1and2', 'ACT', 'CTT', 'TTC', 'TCA']
Updated Sequence: [17, 56, 100, 55, 96]


In [72]:
X_boot = np.array(seqs_out)
y_boot = np.array(y_boot)

In [89]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
X_train,X_other,y_train,y_other = train_test_split(X_boot,y_boot,train_size=0.80,stratify=y_boot,random_state=3)
X_val,X_test,y_val,y_test = train_test_split(X_other,y_other,train_size=0.5,stratify=y_other,random_state=3)

In [90]:
import numpy as np
import tensorflow as tf
from transformer import TransformerEncoder
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam


# Testing model
encoder = TransformerEncoder(
    vocab_size=170,
    emb_sz=64,
    num_of_blocks=1,
    num_of_atten_heads=4)

encoder.compile(
    optimizer = Adam(learning_rate=0.001),
    loss = BinaryCrossentropy(from_logits=False),
    metrics=['acc']
)
encoder.fit(
    X_train,y_train,
    epochs=5,batch_size=100,
    validation_data=(X_val,y_val)
)

Epoch 1/5
109/109 [==============================] - 609s 6s/step - loss: 3.4250 - acc: 0.6723 - val_loss: 2.0165 - val_acc: 0.7868
Epoch 2/5
109/109 [==============================] - 637s 6s/step - loss: 0.7781 - acc: 0.7296 - val_loss: 0.4964 - val_acc: 0.8316
Epoch 3/5
109/109 [==============================] - 506s 5s/step - loss: 0.8821 - acc: 0.7480 - val_loss: 1.0380 - val_acc: 0.5022
Epoch 4/5
109/109 [==============================] - 517s 5s/step - loss: 0.5049 - acc: 0.8074 - val_loss: 0.6003 - val_acc: 0.6890
Epoch 5/5
109/109 [==============================] - 575s 5s/step - loss: 0.5064 - acc: 0.8131 - val_loss: 0.5665 - val_acc: 0.8294


In [91]:
encoder.evaluate(
    X_test,y_test,batch_size=100
)

14/14 [==============================] - 27s 2s/step - loss: 0.5679 - acc: 0.8331


[0.5678842067718506, 0.833088219165802]

In [92]:
encoder.save('encoder.k3.R3.mod',save_format="tf")

INFO:tensorflow:Assets written to: encoder.k3.R3.mod/assets


INFO:tensorflow:Assets written to: encoder.k3.R3.mod/assets


In [35]:
import pandas as pd

out = pd.DataFrame(y)
baseline = out.value_counts()[0] / out.value_counts().sum()
print("Baseline Acc:",baseline)

Baseline Acc: 0.7711924023918396


In [19]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0
